aws:
  access_key_id:      ENV[AWS_ACCESS_KEY_ID]
  secret_access_key:  ENV[AWS_SECRET_ACCESS_KEY]
  region:             'us-west-2'


:concurrency: 25
:pidfile: tmp/pids/shoryuken.pid
:queues:
  - default
  - [smart_tools_convert_video, 2]